/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

package view;

import java.awt.Color;
import model.UsuarioDAO;

/**
 *
 * @author Windows
 */
public class RecuperarContraseña extends javax.swing.JDialog {

    /** Creates new form RecuperarContraseña */
    public RecuperarContraseña(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public RecuperarContraseña(){
        initComponents();
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTFnuevaContra = new javax.swing.JTextField();
        jTFusuario = new javax.swing.JTextField();
        jTFrepcontra = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        butAceptar = new javax.swing.JButton();
        butCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTFnuevaContra.setText(org.openide.util.NbBundle.getMessage(RecuperarContraseña.class, "RecuperarContraseña.jTFnuevaContra.text")); // NOI18N
        jPanel1.add(jTFnuevaContra, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 220, 30));

        jTFusuario.setText(org.openide.util.NbBundle.getMessage(RecuperarContraseña.class, "RecuperarContraseña.jTFusuario.text")); // NOI18N
        jPanel1.add(jTFusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 300, 220, 30));

        jTFrepcontra.setForeground(new java.awt.Color(153, 153, 153));
        jTFrepcontra.setText(org.openide.util.NbBundle.getMessage(RecuperarContraseña.class, "RecuperarContraseña.jTFrepcontra.text")); // NOI18N
        jTFrepcontra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTFrepcontraMousePressed(evt);
            }
        });
        jTFrepcontra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFrepcontraActionPerformed(evt);
            }
        });
        jPanel1.add(jTFrepcontra, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 220, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/recuperarcontraseña (1).jpg"))); // NOI18N
        jLabel1.setText(org.openide.util.NbBundle.getMessage(RecuperarContraseña.class, "RecuperarContraseña.jLabel1.text")); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 500));

        butAceptar.setText(org.openide.util.NbBundle.getMessage(RecuperarContraseña.class, "RecuperarContraseña.butAceptar.text")); // NOI18N
        butAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(butAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 400, 110, 90));

        butCancelar.setText(org.openide.util.NbBundle.getMessage(RecuperarContraseña.class, "RecuperarContraseña.butCancelar.text")); // NOI18N
        butCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(butCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 400, 110, 90));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFrepcontraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFrepcontraMousePressed
        if (jTFrepcontra.getText().equals("Repita su contraseña")) {
            jTFrepcontra.setText("");
            jTFrepcontra.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_jTFrepcontraMousePressed

    private void jTFrepcontraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFrepcontraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFrepcontraActionPerformed

    private void butCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_butCancelarActionPerformed

    private void butAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAceptarActionPerformed
        String usuario = jTFusuario.getText();
        String nuevacontraseña = jTFnuevaContra.getText();
        UsuarioDAO.actualizaContraseña(usuario, nuevacontraseña);
        dispose();
    }//GEN-LAST:event_butAceptarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecuperarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecuperarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecuperarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecuperarContraseña.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                RecuperarContraseña dialog = new RecuperarContraseña(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butAceptar;
    private javax.swing.JButton butCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTFnuevaContra;
    private javax.swing.JTextField jTFrepcontra;
    private javax.swing.JTextField jTFusuario;
    // End of variables declaration//GEN-END:variables

}
