/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import java.awt.Color;
import model.Usuario;
import model.UsuarioDAO;

/**
 *
 * @author Windows
 */
public class Registrarse extends javax.swing.JDialog {

    /**
     * Creates new form Registrarse
     */
    public Registrarse(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    public Registrarse(){
        initComponents();
        transparencia();
        
    }
    public void transparencia (){
        butAceptar.setOpaque(false);
        butAceptar.setContentAreaFilled(false);
        butAceptar.setBorderPainted(false);
        butCancelar.setOpaque(false);
        butCancelar.setContentAreaFilled(false);
        butCancelar.setBorderPainted(false);
    }
//    public Registrarse(){
//        initComponents();
//        PlaceholderTF rc1= new PlaceholderTF("Repetir contraseña");
//        jPanel1.add(rc1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 280, 30));
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTFnombre = new javax.swing.JTextField();
        jTFusuario = new javax.swing.JTextField();
        jTFcontra = new javax.swing.JTextField();
        jTFrepcontra = new javax.swing.JTextField();
        jTFedad = new javax.swing.JTextField();
        FondoRegistro = new javax.swing.JLabel();
        butAceptar = new javax.swing.JButton();
        butCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTFnombre.setText(org.openide.util.NbBundle.getMessage(Registrarse.class, "Registrarse.jTFnombre.text")); // NOI18N
        jPanel1.add(jTFnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, 280, 30));

        jTFusuario.setText(org.openide.util.NbBundle.getMessage(Registrarse.class, "Registrarse.jTFusuario.text")); // NOI18N
        jPanel1.add(jTFusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 190, 280, 30));

        jTFcontra.setText(org.openide.util.NbBundle.getMessage(Registrarse.class, "Registrarse.jTFcontra.text")); // NOI18N
        jPanel1.add(jTFcontra, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 230, 280, 30));

        jTFrepcontra.setForeground(new java.awt.Color(153, 153, 153));
        jTFrepcontra.setText(org.openide.util.NbBundle.getMessage(Registrarse.class, "Registrarse.jTFrepcontra.text")); // NOI18N
        jTFrepcontra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTFrepcontraMousePressed(evt);
            }
        });
        jTFrepcontra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFrepcontraActionPerformed(evt);
            }
        });
        jPanel1.add(jTFrepcontra, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 280, 30));

        jTFedad.setText(org.openide.util.NbBundle.getMessage(Registrarse.class, "Registrarse.jTFedad.text")); // NOI18N
        jPanel1.add(jTFedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 280, 30));

        FondoRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/3639829 (1) (1).jpg"))); // NOI18N
        FondoRegistro.setText(org.openide.util.NbBundle.getMessage(Registrarse.class, "Registrarse.FondoRegistro.text")); // NOI18N
        jPanel1.add(FondoRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        butAceptar.setText(org.openide.util.NbBundle.getMessage(Registrarse.class, "Registrarse.butAceptar.text")); // NOI18N
        butAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAceptarActionPerformed(evt);
            }
        });
        jPanel1.add(butAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 422, 80, 70));

        butCancelar.setText(org.openide.util.NbBundle.getMessage(Registrarse.class, "Registrarse.butCancelar.text")); // NOI18N
        butCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(butCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, 70, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTFrepcontraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFrepcontraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFrepcontraActionPerformed

    private void jTFrepcontraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTFrepcontraMousePressed
        if (jTFrepcontra.getText().equals("Repita su contraseña")) {
            jTFrepcontra.setText("");
            jTFrepcontra.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_jTFrepcontraMousePressed

    private void butAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAceptarActionPerformed
        Usuario u1 = new Usuario();

        u1.setId(0);
        u1.setNombre(jTFnombre.getText());
        u1.setUsuario(jTFusuario.getText());
        u1.setContraseña(jTFcontra.getText());
        u1.setEdad(Integer.parseInt(jTFedad.getText()));

        UsuarioDAO.crearUsuario(u1);

        dispose();
    }//GEN-LAST:event_butAceptarActionPerformed

    private void butCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_butCancelarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Registrarse dialog = new Registrarse(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FondoRegistro;
    private javax.swing.JButton butAceptar;
    private javax.swing.JButton butCancelar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTFcontra;
    private javax.swing.JTextField jTFedad;
    private javax.swing.JTextField jTFnombre;
    private javax.swing.JTextField jTFrepcontra;
    private javax.swing.JTextField jTFusuario;
    // End of variables declaration//GEN-END:variables
}
